name: eventizer
description: A social App

version: 1.0.0+1

module:
  androidX: true

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  image_editor: ^0.1.6
  extended_image: ^0.7.2
  splashscreen: ^1.2.0
  get_it: ^4.0.2
  line_awesome_icons: ^1.0.4+2
  font_awesome_flutter: ^8.8.1
  provider: ^4.0.5+1
  dash_chat: ^1.1.2
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.5
  firebase_storage: ^3.1.5
  image_picker: ^0.6.5+2
  flutter_search_panel: ^1.0.1
  #find_dropdown: ^0.1.7+1
  fluttertoast: ^4.0.1
  #loading screen packages
  flutter_spinkit: ^4.1.2+1
  simple_animations: ^2.1.0
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/icons/

  uses-material-design: true

  fonts:
    - family: IndieFlower
      fonts:
        - asset: assets/fonts/IndieFlower-Regular.ttf
    - family: Zona
      fonts:
        - asset: assets/fonts/ZonaPro-Bold.otf
    - family: ZonaLight
      fonts:
        - asset: assets/fonts/ZonaPro-ExtraLight.otf
