name: eventizer
description: A social App

publish_to: 'none'

version: 0.1.4+5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  package_info: ^0.4.1
  fancy_bottom_navigation: ^0.3.2
  image_editor: ^0.7.0
  extended_image: ^0.9.0
  splashscreen: ^1.2.0
  get_it: ^4.0.2
  line_awesome_icons: ^1.0.4+2
  font_awesome_flutter: ^8.8.1
  provider: ^4.1.3
  dash_chat: ^1.1.8
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.6
  firebase_storage: ^3.1.6
  image_picker: ^0.6.7+1
  searchable_dropdown: ^1.1.3
  fluttertoast: ^4.0.1
  store_redirect: ^1.0.2
  #loading screen packages
  flutter_spinkit: ^4.1.2+1
  simple_animations: ^2.2.1
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/icons/

  uses-material-design: true

  fonts:
    - family: IndieFlower
      fonts:
        - asset: assets/fonts/IndieFlower-Regular.ttf
    - family: Zona
      fonts:
        - asset: assets/fonts/ZonaPro-Bold.otf
    - family: ZonaLight
      fonts:
        - asset: assets/fonts/ZonaPro-ExtraLight.otf
