name: eventizer
description: A social App


version: 1.0.0+1

module:
  androidX: true

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  image_editor: ^0.1.6
  extended_image: ^0.7.1
  splashscreen: ^1.2.0
  get_it: ^3.1.0
  line_awesome_icons: ^1.0.4+2
  font_awesome_flutter: ^8.5.0
  provider: ^4.0.1
  dash_chat: ^1.0.15
  firebase_auth: ^0.15.4
  cloud_firestore: ^0.13.0+1
  firebase_storage: ^3.1.1
  image_picker: ^0.6.3+1
  flutter_search_panel: ^1.0.1
  #find_dropdown: ^0.1.7+1
  fluttertoast: ^3.1.3
  #loading screen package
  flutter_spinkit: "^4.1.1"
  simple_animations: ^1.3.3
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/images/

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: IndieFlower
      fonts:
        - asset: fonts/IndieFlower-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
