name: eventizer
description: Create or join an event
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.1.5+6

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  dropdown_search: ^3.0.1
  url_launcher: ^6.1.0
  package_info: ^2.0.2
  fancy_bottom_navigation: ^0.3.2
  image_editor: ^1.0.2
  extended_image: ^6.0.3
  splashscreen: ^1.2.0
  get_it: ^7.2.0
  line_awesome_icons: ^1.0.4+2
  font_awesome_flutter: ^10.1.0
  provider: ^6.0.2
  dash_chat: ^1.1.14
  image_picker: ^0.8.5
  fluttertoast: ^8.0.9
  store_redirect: ^2.0.1
  #loading screen packages
  flutter_spinkit: ^5.1.0
  simple_animations: ^4.0.2
  #firebase
  firebase_core: ^1.16.0
  firebase_auth: ^3.3.17
  cloud_firestore: ^3.1.14
  firebase_storage: ^10.2.15
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  


flutter:
  assets:
    - assets/images/
    - assets/icons/
  
  uses-material-design: true
  fonts:
    - family: IndieFlower
      fonts:
        - asset: assets/fonts/IndieFlower-Regular.ttf
    - family: Zona
      fonts:
        - asset: assets/fonts/ZonaPro-Bold.otf
    - family: ZonaLight
      fonts:
        - asset: assets/fonts/ZonaPro-ExtraLight.otf
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
