/// Flutter icons EventizerIconSet
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  EventizerIconSet
///      fonts:
///       - asset: fonts/EventizerIconSet.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class EventizerIconSet {
  EventizerIconSet._();

  static const _kFontFam = 'EventizerIconSet';

  static const IconData explore = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData user = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData chat = const IconData(0xe802, fontFamily: _kFontFam);
}
